extends: airbnb

env:
  node:  true
  mocha: true

parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: script

rules:
  strict:
    - 2
    - global

  key-spacing:
    - 2
    -
      mode:        "minimum"
      align:       "value"
      beforeColon: false
  no-multi-spaces:
    - 0
    -
      exceptions:
        ImportDeclaration:        true
        VariableDeclarator:       true
        ArrowFunctionExpression:  true
  comma-dangle:
    - error
    - never
  max-len:
    - 2
    - code: 150
  no-confusing-arrow:
    - error
    - allowParens: true

  no-param-reassign:    0
  no-return-assign:     0
  no-use-before-define: off
